# Generated by Django 4.1 on 2022-08-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['created_time', 'last_modified']},
        ),
        migrations.AddField(
            model_name='notice',
            name='context',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='notice',
            name='created_user',
            field=models.CharField(default='사용자', max_length=100),
        ),
        migrations.AlterField(
            model_name='notice',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
