# Generated by Django 4.1 on 2022-08-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_alter_notice_options_notice_context_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
